version: '2'
services:
    blast-app:
        image: blast
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://blast-postgresql:5432/blast
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blast-postgresql:
        extends:
            file: postgresql.yml
            service: blast-postgresql
